---
title: マサチ
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: https://masachi.github.io
google-tracking-id: UA-97018813-1
force-https: true
lang: zh
author: Masachi Zhang
description: これからもよろしくおねがいします
keywords: personal, jekyll, theme
favicon: "/img/favicon.ico"
black-favicon: "/img/black-lab-glass.ico"
background-img: "../img/intro-bg.jpg"
dynamic-typing: true
shuffle: true
loop: true
loop-count: false
type-speed: 10
start-delay: 200
delete-delay: 5000
lines:
- text: 这个辣鸡blog里面什么都没有
- text: '2333333333333333333333'
- text: wolow，向dalao们低头
me-img: "/img/jetpacktocat.png"
color-browser: "#000000"
apple-status-bar-style: black
web-app-mode: true
icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"
enable-gesture-navigation: true
post-preview-words: 96
paginate: 5
email-share: true
fb-share: true
twitter-share: true
linkedin-share: true
reddit-share: true
google-plus-share: true
tumblr-share: true
pinterest-share: true
pocket-share: true
vkontakte-share: true
disqus-shortname: masachi
syntax-highlight: true
timeline-img: "/img/timeline/default.png"
email: zhangjb42@gmail.com
author_blurb: ''
author_blurb_image: "/img/author.png"
social:
- title: weibo
  url: http://weibo.com/u/2233262487
- title: facebook
  url: https://www.facebook.com/profile.php?id=100009534794910
- title: twitter
  url: https://twitter.com/MasachiZhang
- title: github
  url: https://github.com/masachi
- title: wechat
  url: 
err-404-img: "/img/labtocat.png"
keybase-username: masachizhang
keybase-in-social: false
keybase-in-footer: false
pages_list:
  关于: about
  最新博客: latest-post
  时间线: timeline
  联系我: contact
exclude:
- LICENSE
- README.md
- CONTRIBUTING
- CONTRIBUTORS
- scripts
paginate_path: blog/page:num/
sass:
  style: compressed
gems:
- jekyll-paginate
- jemoji
- jekyll-admin
- jekyll-polyglot
- jekyll-feed
